<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>29c00112-62d9-44c1-9ebf-fc0c310db1fe</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AI_Chat_App.Core\AI_Chat_App.Core.csproj" />
  </ItemGroup>

</Project>
